package repeater

import com.fasterxml.jackson.databind.DeserializationFeature
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory
import com.fasterxml.jackson.module.kotlin.readValue
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import org.slf4j.LoggerFactory
import java.nio.file.Files
import java.nio.file.Path
import java.security.SecureRandom

data class PodcastConfig(
    val id: String,
    val url: String,
    val title: String? = null,
    // Overrides the global transcode section for this podcast when set.
    val transcode: TranscodeConfig? = null,
)

data class UserConfig(
    val name: String,
)

data class TranscodeConfig(
    // When true, downloaded episodes are re-encoded to save disk space
    // (typically 50-75% smaller). Requires ffmpeg on the PATH.
    // Episodes already in the cache are not touched.
    val enabled: Boolean = false,
    // "opus": best compression, plays in most podcatchers (gPodder,
    //         AntennaPod...) but NOT in iOS/Apple Podcasts.
    // "aac":  AAC in an m4a container, plays everywhere including iOS.
    val codec: String = "opus",
    // For opus, 32 is comfortable for speech; for aac use 64 or higher.
    val bitrateKbps: Int = 32,
)

data class AppConfig(
    val port: Int = 8080,
    // Optional. When unset, links in mirrored feeds are built from the Host
    // header of the incoming request, which is usually what you want.
    val baseUrl: String? = null,
    val podcasts: List<PodcastConfig> = emptyList(),
    val users: List<UserConfig> = emptyList(),
    val transcode: TranscodeConfig = TranscodeConfig(),
)

/**
 * Loads config.yaml from the data directory and manages generated user keys.
 *
 * Keys live in a separate generated file (generated/user-keys.yaml) so that
 * config.yaml stays purely hand-edited: you add a user by name, the server
 * generates and remembers the key for that name.
 */
class ConfigStore(private val dataDir: Path) {
    private val log = LoggerFactory.getLogger(ConfigStore::class.java)
    private val yaml: ObjectMapper = ObjectMapper(YAMLFactory())
        .registerKotlinModule()
        .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)

    val configFile: Path = dataDir.resolve("config.yaml")
    private val keysFile: Path = dataDir.resolve("generated").resolve("user-keys.yaml")

    @Volatile
    var config: AppConfig = AppConfig()
        private set

    /** user name -> generated key */
    @Volatile
    var userKeys: Map<String, String> = emptyMap()
        private set

    fun load() {
        if (!Files.exists(configFile)) {
            error("Config file not found: $configFile")
        }
        val loaded = yaml.readValue<AppConfig>(configFile.toFile())

        val duplicateIds = loaded.podcasts.groupBy { it.id }.filterValues { it.size > 1 }.keys
        require(duplicateIds.isEmpty()) { "Duplicate podcast ids in config: $duplicateIds" }
        val transcodeSections = listOf("transcode" to loaded.transcode) +
            loaded.podcasts.mapNotNull { p -> p.transcode?.let { "podcasts[${p.id}].transcode" to it } }
        for ((where, t) in transcodeSections) {
            require(t.codec in setOf("opus", "aac")) { "$where.codec must be \"opus\" or \"aac\", got \"${t.codec}\"" }
            require(t.bitrateKbps in 6..510) { "$where.bitrateKbps must be between 6 and 510, got ${t.bitrateKbps}" }
        }

        config = loaded
        userKeys = loadOrGenerateKeys(loaded.users)
        log.info(
            "Config loaded from {}: {} podcast(s), {} user(s)",
            configFile, loaded.podcasts.size, loaded.users.size
        )
    }

    fun podcast(id: String): PodcastConfig? = config.podcasts.find { it.id == id }

    /** Returns the user name that owns this key, or null if the key is unknown. */
    fun userForKey(key: String): String? =
        userKeys.entries.find { it.value == key }?.key

    private fun loadOrGenerateKeys(users: List<UserConfig>): Map<String, String> {
        val existing: Map<String, String> =
            if (Files.exists(keysFile)) yaml.readValue(keysFile.toFile()) else emptyMap()

        val keys = existing.toMutableMap()
        for (user in users) {
            if (user.name !in keys) {
                keys[user.name] = newKey()
                log.info("Generated key for new user '{}': {}", user.name, keys[user.name])
            }
        }

        if (keys != existing) {
            Files.createDirectories(keysFile.parent)
            val header = "# Generated by the server. One key per user from config.yaml.\n" +
                "# Delete a line and reload to force a new key for that user.\n"
            Files.writeString(
                keysFile,
                header + keys.entries.joinToString("") { "${it.key}: ${it.value}\n" }
            )
        }

        // Only users still present in config.yaml may access the server, even
        // if old keys remain in the generated file.
        val active = users.map { it.name }.toSet()
        return keys.filterKeys { it in active }
    }

    private fun newKey(): String {
        val bytes = ByteArray(16)
        SecureRandom().nextBytes(bytes)
        return bytes.joinToString("") { "%02x".format(it) }
    }
}
